name: myflutter
description: A Flutter Android jewellery invoicing application built with GitHub Codespaces.
publish_to: 'none'
version: 1.0.1+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  pdf: ^3.11.0
  printing: ^5.13.0
  shared_preferences: ^2.3.0
  intl: ^0.19.0
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

dependency_overrides:
  win32: ^5.0.0
  archive: ^4.0.0

flutter:
  uses-material-design: true
