name: myflutter
description: A Flutter Android jewellery invoicing application built with GitHub Codespaces.
publish_to: 'none'
version: 1.0.1+2

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  pdf: ^3.9.0
  printing: ^5.9.0
  shared_preferences: ^2.0.15
  intl: ^0.18.0
  path_provider: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
